// Поля характеристик по категориям. Используется и формой подачи (/submit),
// и формой редактирования (/my-listings/[id]/edit) — единый источник правды.
export type Field = { name: string; label: string; type?: string; placeholder?: string; options?: string[] };

export const categoryFields: Record<number, Field[]> = {
  1: [
    { name: 'vehicle_type', label: 'Тип ТС', type: 'select', options: ['Легковая', 'Грузовая', 'Мотоцикл', 'Автобус', 'Спецтехника'] },
    { name: 'brand', label: 'Марка', placeholder: 'Toyota, BMW, VW...' },
    { name: 'model', label: 'Модель', placeholder: 'Camry, X5, Golf...' },
    { name: 'year', label: 'Год выпуска', type: 'number', placeholder: '2019' },
    { name: 'mileage', label: 'Пробег (км)', type: 'number', placeholder: '85000' },
    { name: 'engine', label: 'Объём двигателя (л)', type: 'number', placeholder: '2.0' },
    { name: 'power', label: 'Мощность (л.с.)', type: 'number', placeholder: '150' },
    { name: 'fuel', label: 'Тип топлива', type: 'select', options: ['Бензин', 'Дизель', 'Электро', 'Гибрид', 'Газ'] },
    { name: 'transmission', label: 'Коробка передач', type: 'select', options: ['Автомат', 'Механика', 'Робот', 'Вариатор'] },
    { name: 'drive', label: 'Привод', type: 'select', options: ['Передний', 'Задний', 'Полный'] },
    { name: 'body', label: 'Кузов', type: 'select', options: ['Седан', 'Хэтчбек', 'Универсал', 'Внедорожник', 'Купе', 'Кабриолет', 'Минивэн', 'Пикап'] },
    { name: 'color', label: 'Цвет', placeholder: 'Чёрный, Белый, Серый...' },
    { name: 'condition', label: 'Состояние', type: 'select', options: ['Новое', 'Б/у', 'На запчасти'] },
    { name: 'owners', label: 'Количество владельцев', type: 'number', placeholder: '1' },
    { name: 'customs', label: 'Таможня', type: 'select', options: ['Растаможен', 'Не растаможен'] },
  ],
  2: [
    { name: 'property_type', label: 'Тип недвижимости', type: 'select', options: ['Квартира', 'Дом', 'Комната', 'Участок', 'Коммерческая', 'Гараж'] },
    { name: 'deal_type', label: 'Операция', type: 'select', options: ['Продажа', 'Аренда'] },
    { name: 'area_total', label: 'Общая площадь (м²)', type: 'number', placeholder: '52' },
    { name: 'area_living', label: 'Жилая площадь (м²)', type: 'number', placeholder: '32' },
    { name: 'area_kitchen', label: 'Площадь кухни (м²)', type: 'number', placeholder: '10' },
    { name: 'rooms', label: 'Количество комнат', type: 'number', placeholder: '2' },
    { name: 'floor', label: 'Этаж', type: 'number', placeholder: '4' },
    { name: 'total_floors', label: 'Этажей в доме', type: 'number', placeholder: '9' },
    { name: 'building_type', label: 'Тип здания', type: 'select', options: ['Панельный', 'Кирпичный', 'Новостройка', 'Деревянный', 'Монолитный'] },
    { name: 'build_year', label: 'Год постройки', type: 'number', placeholder: '1985' },
    { name: 'condition', label: 'Состояние', type: 'select', options: ['Без ремонта', 'Косметический ремонт', 'Евроремонт', 'Дизайнерский'] },
    { name: 'furniture', label: 'Мебель', type: 'select', options: ['С мебелью', 'Без мебели', 'Частично'] },
    { name: 'balcony', label: 'Балкон', type: 'select', options: ['Есть', 'Нет'] },
    { name: 'elevator', label: 'Лифт', type: 'select', options: ['Есть', 'Нет'] },
    { name: 'parking', label: 'Парковка', type: 'select', options: ['Есть', 'Нет', 'Гараж'] },
    { name: 'heating', label: 'Отопление', type: 'select', options: ['Центральное', 'Автономное', 'Электрическое'] },
  ],
  3: [
    { name: 'sphere', label: 'Сфера', type: 'select', options: ['IT', 'Медицина', 'Строительство', 'Торговля', 'Образование', 'Транспорт', 'Производство', 'Финансы', 'Юриспруденция', 'Другое'] },
    { name: 'employment', label: 'Тип занятости', type: 'select', options: ['Полный день', 'Частичная занятость', 'Удалённо', 'Проектная', 'Стажировка'] },
    { name: 'schedule', label: 'График работы', type: 'select', options: ['5/2', '2/2', 'Свободный', 'Сменный'] },
    { name: 'salary_from', label: 'Зарплата от (€)', type: 'number', placeholder: '1000' },
    { name: 'salary_to', label: 'Зарплата до (€)', type: 'number', placeholder: '2000' },
    { name: 'experience', label: 'Опыт', type: 'select', options: ['Без опыта', 'От 1 года', 'От 3 лет', 'От 5 лет'] },
    { name: 'education', label: 'Образование', type: 'select', options: ['Не требуется', 'Среднее', 'Среднее специальное', 'Высшее'] },
    { name: 'language', label: 'Язык', type: 'select', options: ['Латышский', 'Русский', 'Английский', 'Латышский + Русский', 'Несколько языков'] },
  ],
  4: [
    { name: 'subcategory', label: 'Подкатегория', type: 'select', options: ['Телефоны', 'Ноутбуки', 'Планшеты', 'Телевизоры', 'Фото/Видео', 'Игровые консоли', 'Комплектующие', 'Аудио', 'Умный дом'] },
    { name: 'brand', label: 'Бренд', placeholder: 'Apple, Samsung, Sony...' },
    { name: 'model', label: 'Модель', placeholder: 'iPhone 14 Pro' },
    { name: 'year', label: 'Год выпуска', type: 'number', placeholder: '2023' },
    { name: 'memory', label: 'Память / Объём', placeholder: '256GB, 16GB RAM...' },
    { name: 'color', label: 'Цвет', placeholder: 'Space Black, White...' },
    { name: 'condition', label: 'Состояние', type: 'select', options: ['Новое', 'Как новое', 'Хорошее', 'Удовлетворительное', 'На запчасти'] },
    { name: 'completeness', label: 'Комплектация', type: 'select', options: ['Полная', 'Без коробки', 'Только устройство'] },
  ],
  5: [
    { name: 'subcategory', label: 'Подкатегория', type: 'select', options: ['Мебель', 'Бытовая техника', 'Посуда', 'Декор', 'Инструменты', 'Сантехника', 'Освещение', 'Текстиль'] },
    { name: 'brand', label: 'Бренд', placeholder: 'IKEA, Bosch, Samsung...' },
    { name: 'color', label: 'Цвет', placeholder: 'Белый, Серый, Чёрный...' },
    { name: 'material', label: 'Материал', placeholder: 'Дерево, металл, ткань...' },
    { name: 'dimensions', label: 'Размеры (ДxШxВ)', placeholder: '200x90x75 см' },
    { name: 'condition', label: 'Состояние', type: 'select', options: ['Новое', 'Как новое', 'Хорошее', 'Б/у'] },
  ],
  6: [
    { name: 'subcategory', label: 'Подкатегория', type: 'select', options: ['Одежда', 'Обувь', 'Аксессуары', 'Украшения', 'Часы', 'Сумки'] },
    { name: 'for_whom', label: 'Для кого', type: 'select', options: ['Мужское', 'Женское', 'Детское', 'Унисекс'] },
    { name: 'brand', label: 'Бренд', placeholder: 'Nike, Zara, Gucci...' },
    { name: 'size', label: 'Размер', placeholder: 'M, 42, XL, 38EU...' },
    { name: 'color', label: 'Цвет', placeholder: 'Чёрный, Синий...' },
    { name: 'condition', label: 'Состояние', type: 'select', options: ['Новое с бирками', 'Новое без бирок', 'Отличное', 'Хорошее', 'Б/у'] },
  ],
  7: [
    { name: 'subcategory', label: 'Подкатегория', type: 'select', options: ['Спорт', 'Музыкальные инструменты', 'Книги', 'Коллекционирование', 'Рыбалка', 'Охота', 'Туризм', 'Велосипеды', 'Игры'] },
    { name: 'brand', label: 'Бренд', placeholder: '' },
    { name: 'model', label: 'Модель / Название', placeholder: '' },
    { name: 'year', label: 'Год', type: 'number', placeholder: '2022' },
    { name: 'condition', label: 'Состояние', type: 'select', options: ['Новое', 'Как новое', 'Хорошее', 'Б/у'] },
  ],
  8: [
    { name: 'animal_type', label: 'Вид животного', type: 'select', options: ['Собака', 'Кошка', 'Птица', 'Рыба', 'Грызун', 'Рептилия', 'Другое'] },
    { name: 'breed', label: 'Порода', placeholder: 'Лабрадор, Мейн-кун...' },
    { name: 'age', label: 'Возраст', placeholder: '2 месяца, 3 года...' },
    { name: 'gender', label: 'Пол', type: 'select', options: ['Мальчик', 'Девочка'] },
    { name: 'color', label: 'Окрас', placeholder: 'Золотистый, Чёрно-белый...' },
    { name: 'vaccinated', label: 'Вакцинация', type: 'select', options: ['Да', 'Нет', 'Частично'] },
    { name: 'documents', label: 'Документы', type: 'select', options: ['Есть', 'Нет'] },
    { name: 'sterilized', label: 'Стерилизация', type: 'select', options: ['Да', 'Нет'] },
  ],
};
